### ISSUE TITLE
Configuração da plataforma conforme o README

### ISSUE THREAD

**Issue by egabrielnunes** [ufalenactus/EnactusAdmin#1]
- [x] Ana
- [x] Gregory

**Comment by egabrielnunes** [comment]
@gregoryalbertt @anageorgia posso tentar ajudar em algo? podem colocar o print dos problemas aqui para eu tentar ajudar a solucionar.

**Comment by anageorgia** [comment]
Resolvido!

**Comment by egabrielnunes** [comment]
Conversei com o Greg e semana passada ele solucionou esse problema, @gregoryalbertt coloca a data aqui de quando vc resolveu isso, please.
